### ISSUE TITLE
Brightness adjustment doesn't work for TFT

### ISSUE THREAD

**Issue by melkati** [melkati/CO2-Gadget#125]
**CO2 Gadget version and flavour**

```
-->[STUP] CO2 Gadget Version: 0.8.009-development Flavour: TTGO T-Display Sandwich (Git HEAD: 943e3d7)
-->[STUP] Version compiled: Jan 17 2024 at 09:42:30
```

**CO2 Gadget installation method?**

All

**Describe the bug**
Brightness adjustment doesn't work for TFT. It was working if v0.6

**Comment by melkati** [comment]
I don't understand what's happening with brightness...

Spent four hours debugging without success, finally flashed 0.6.000 and brightness adjustment is still not working) it was supposed to be working on the old 0.6.000 firmware release)! 

```
-->[MAIN] CO2 Gadget Version: 0.6.000 Flavour: TTGO T-Display Sandwich
```

May be there was a change in third party libraries?

Top image is  0.8.000 bottom is 0.6.000:

![photo_2024-01-17_09-50-37](https://github.com/melkati/CO2-Gadget/assets/11509521/4581ea7e-6eca-45c9-82e0-d69f20c97408)

**Comment by melkati** [comment]
I think last commit fixes the bug for TTGO T-Display (both brightness adjustment and screen off by time).

T-Display S3 has a different way to adjust brightness in just 16 steps with an "intelligent chip" to control it.

**Comment by melkati** [comment]
I think last commit fixes the bug for the T-Display S3 not turning off the display backlight after the defined time when configured to do so.

This fix does not implement brightness regulation for T-Display S3.

I'll close this issue and add to the roadmap to implement brightness regulation for T-Display S3.

**Comment by melkati** [comment]
Fixed with #144

**Comment by melkati** [comment]
Is pending to map brightness from 0 to 255 to 0 to 100 to make it more user friendly.
